[package]
name = "lgpd-rest-prototipo"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
utoipa = "5.4.0"
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
utoipa-actix-web = "0.1.2"

