[project]
name = "lgpd-rest-prototipo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.120.4",
    "pymongo==4.13.1",
]
